apiVersion: v1
kind: Service
metadata:
  name: neonio-web
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: neonio-web
  ports:
    - port: 3000
      nodePort: 32276
  selector:
    app: neonio-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neonio-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: neonio-web
  replicas: {{ .Values.web.servers }}
  template:
    metadata:
      labels:
        app: neonio-web
    spec:
      containers:
      - name: neonio-web
        imagePullPolicy: {{ .Values.web.pullPlociy }}
        image: "{{ .Values.web.repository }}:{{ .Values.web.tag }}"
        env :
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace 
        - name: PROMETHEUS_ENABLED
          value: "{{ .Values.web.prometheus }}"
        - name: ALTERMANAGER_ENABLED
          value: "{{ .Values.web.alertmanager }}"
        - name: PROMETHEUS_SVC
          value: "{{ .Values.web.prometheus_svc }}"
        - name: ALTERMANAGER_SVC
          value: "{{ .Values.web.alertmanager_svc }}"
        command:
        - sh
        - -c
        - "/opt/neonsan/bin/start_web.sh"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp |grep -w 3000"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "netstat -anp |grep -w 3000"
          initialDelaySeconds: 10
          timeoutSeconds: 5       
                     